// Retrieve all users
###
GET http://localhost:8080/users

// Create a user
###
POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "Timo",
    "email": "123@gmail.com",
    "age": 35
}

// Retrieve a user (this request is not obligatory) 
###
GET http://localhost:8080/users/admin

// Change an existing user
###
PUT http://localhost:8080/users/manfred
Content-Type: application/json

{
    "name": "Marina",
    "email": "S4566@gmail.com"
}

// Delete a user
###
DELETE  http://localhost:8080/users/manfred


